#!/usr/bin/env bash
echo "== create bucket"

if [ -z "$1" ]; then
    echo "Bucket name not sent"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--bucket-namespace account-regional \
--query Location \
--output text